### ISSUE TITLE
Remove "Cordova" from everywhere visible

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#10]
- [x] I noticed on first load there is the text "We Vote Cordova" on a blue background. Please remove "Cordova" from anywhere that voters can see it.
- [x] On my phone, the app name that shows under our icon is "We Vote Cordova" (and "WeVoteCordova" in one place). Please make it "We Vote".

**Comment by SailingSteve** [comment]
@DaleMcGrew 
What should the app be called? it is currently "We Vote Voter Guide" in what would show in the App Store.

Should it just be "We Vote"?

**Comment by DaleMcGrew** [comment]
@SailingSteve ideally we can have it called "We Vote Voter Guide" everywhere in the app store *except* under the icon on someone's home screen, where it should just be the shortened "We Vote".

**Comment by SailingSteve** [comment]
@DaleMcGrew You may have to delete the older versions on your phone to see the new one, with "We Vote" as the on screen app name, and "We Vote" on the splash screen.  This will appear when I make build "5" sometime this week.

**Comment by SailingSteve** [comment]
I think this is done.
