### ISSUE TITLE
Update email sign in link to open Cordova (Working in iOS, not in Android)

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#11]
When you request a sign in link within Cordova:
![screen shot 2018-02-12 at 9 53 28 am](https://user-images.githubusercontent.com/7756031/36111367-b8fa67e8-0fda-11e8-9d33-b4d0b88c2eb7.png)

...clicking the link in your email program signs you into the browser version. Update the WeVoteServer api to instead send a link that opens and processes the link from Cordova instead of in a browser on your phone.

**Comment by SailingSteve** [comment]
@DaleMcGrew 
I can do this, but I think it will be confusing.  These links will only work from your phone, and will probably end up in the mailbox on your phone and on your desktop.


"You will receive a magic link in your email inbox. Click that link to be signed into your We Vote account."
**Should become**
"You will receive a magic link in your email inbox on your phone. Click that link to be signed into your We Vote account. This link will only work for email you received on your phone."

**Then the message says:**

Verify Email --  If you did not visit https://WeVote.US, please do not verify your email.                         
You can notify us that there was a problem by forwarding this email to info@WeVote.US.                                          Thank you,

**And it should say**
 
Verify Email --  If you did not send a magic email from your We Vote app, Please do not verify your email.   The link in this email was sent from the We Vote app, and will only work if clicked in the email program on your phone.  You can notify us that there was a problem by forwarding this email to info@WeVote.US.

**Comment by SailingSteve** [comment]
I have something put together today, that should have solved this, but Gmail on Android seems like it is  disabling custom scheme links.
https://productforums.google.com/forum/#!topic/gmail/K06xELRD2uo
There are lots of StackOverflow comments about this, it looks like Gmail purposefully broke this.

I could have it be a link back to the server, that would open a page with a http redirect, like I did with Twitter auth.   Yuck.

**Comment by SailingSteve** [comment]
@DaleMcGrew 
Is the purpose of magic link to recall the Twitter and Facebook authentication data from postgres and to act like you have authenticated with them?  So after signing in once with Twitter, you could delete your twitter account, and send a magic link, and we would still show you as signed into Twitter?  And if you have never signed in with Twitter or FB and you sent a magic link, you would have an authentication with no name or picture or address?

**Comment by SailingSteve** [comment]
The email arrives, and is displayable on the phone, but in the Android Gmail app, the Sign In button doesn't do anything when you click it, but the other links like www.WeVote.US does work.  So it probably needs a python side fix.

**Comment by SailingSteve** [comment]
From the email: 
```html
    <a href=3D"wevotetwitterscheme://sign_in_email/VcH1bwRJN1Za" 
        style=3D"color:#3b5998;text-decoration:none;display:block;">
      <center>
        <font size=3D"3">
          <span style=3D"font-family:Helvetica Neue,Helvetica,Lucida Grande,tahoma,verdana,arial,sans-serif;white-space:nowrap;font-weight:bold;vertical-align:middle;color:#ffffff;text-shadow:0 -1px 0 #415686;font-size:14px;line-height:14px;">
            Sign In
          </span>
        </font>
     </center>
   </a>
```

This looks good, it must be a gmail issue?

**Comment by SailingSteve** [comment]
https://stackoverflow.com/questions/38778618/cant-get-gmail-for-android-to-open-a-custom-url-scheme-or-an-intent-url

His "Update1:" shows a work around, it could hit the api server to return the redirect to a custom scheme.

**Comment by SailingSteve** [comment]
The following page when served from http://podell.com/sp.html and read on Chrome on the android simulator, did not open the app.  The same page in Safari on iOS, opened the app.

```
<!doctype html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Podell</title>
	<meta name="keywords" content="automatic redirection">
</head>
<body>
<h1><a href="wevotetwitterscheme://sign_in_email/VcH1bwRJN1Za">Click</a></h1>
</body>
</html>
```

**Comment by SailingSteve** [comment]
https://developer.chrome.com/multidevice/android/intents
https://stackoverflow.com/questions/41524087/navigation-is-blocked-when-redirecting-from-chrome-custom-tab-to-android-app

**Comment by SailingSteve** [comment]
06-08 16:25:44.769 5720-5720/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "Navigation is unreachable: wevotetwitterscheme://sign_in_email/VcH1bwRJN1Za", source: http://podell.com/sp.html (0)
06-08 16:32:00.786 5720-5720/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "Navigation is blocked: intent://sign_in_email/VcH1bwRJN1Za#Intent;package=org.wevote.cordova;scheme=wevotetwitterscheme;end;", source: http://podell.com/sp.html (0)
06-08 16:32:05.640 5720-5720/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "Navigation is blocked: intent://scan/#Intent;scheme=wevotetwitterscheme;package=org.wevote.cordova;end", source: http://podell.com/sp.html (0)
06-08 16:32:20.454 5720-5720/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "Navigation is blocked: intent://sign_in_email/VcH1bwRJN1Za#Intent;package=org.wevote.cordova;scheme=wevotetwitterscheme;end;", source: http://podell.com/sp.html (0)
06-08 16:33:17.228 5720-5720/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "Navigation is blocked: intent://#Intent;package=org.wevote.cordova;scheme=wevotetwitterscheme;end;", source: http://podell.com/sp.html (0)
06-08 16:33:51.284 5720-5720/com.android.chrome I/chromium: [INFO:CONSOLE(0)] "Navigation is unreachable: intent://package=org.wevote.cordova;scheme=wevotetwitterscheme;end;", source: http://podell.com/sp.html (0)

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve I believe this is related to the Twitter sign in issue that is being reported.
![screen shot 2018-11-06 at 9 45 57 am](https://user-images.githubusercontent.com/7756031/48082982-d63edf00-e1a8-11e8-9774-d57e1e7b9727.png)

**Comment by DaleMcGrew** [comment]
- User: I wanted to share my votes, but this sign in link isn't working? "Please sign in to We Vote so you can save your ballot and invite your friends. If the button does not work, please copy and paste this link into a browser: wevotetwitterscheme://sign_in_email/4FMP<TRUNCATED>"
- Dale: Unfortunately our Twitter sign in from the app is currently broken. :( The sign in by email link works. Once you sign in by email, you can sign in again by email on https://WeVote.US and then sign into Twitter from the browser.
- User: This is actually from the email signin on the mobile app (the twitter and fb login buttons werent' working so I tried email), and for some reason this includes a twitter thing. ("wevotetwitterscheme")
![img_5674](https://user-images.githubusercontent.com/7756031/48087999-b661e800-e1b5-11e8-8f1f-683ff95810df.jpeg)
