### ISSUE TITLE
Lighten text color of the top-most phone utility bar

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#12]
The top-most bar ("Verizon") is currently white. Please make it dark blue and not transparent so we don't get visual glitches like this:
![fullsizerender-2](https://user-images.githubusercontent.com/7756031/36112672-438f7cd2-0fdf-11e8-88c6-13e6a47bb753.jpg)

**Comment by SailingSteve** [comment]
http://devgirl.org/2014/07/31/phonegap-developers-guid/
cordova plugin add org.apache.cordova.statusbar

There is a plugin that handles this -- it crashes during install with a ???

**Comment by DaleMcGrew** [comment]
Hi @SailingSteve, the recent change you made, which prevents the page from showing beneath the "Carrier + Battery" bar, is a great step. Could you please make it the same color as our header, instead of white?

**Comment by SailingSteve** [comment]
The apple menu is black letters, so the result would be black on dark blue.

**Comment by DaleMcGrew** [comment]
We would need to change the apple menu letters to white, like here:
![fullsizerender](https://user-images.githubusercontent.com/7756031/36924145-66d96c6a-1e22-11e8-9805-504c26740324.jpeg)

**Comment by SailingSteve** [comment]
LOL:  Most of the last 10 apps I looked at had the hamburger in the upper left.
Also that Wells app might be swift/objective c, but I can look into changing the color.

**Comment by SailingSteve** [comment]
I can do it, pretty easy
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-statusbar/

**Comment by DaleMcGrew** [comment]
You rock!

**Comment by SailingSteve** [comment]
Well it would have been easy if it worked.
https://issues.apache.org/jira/browse/CB-13843
We can wait for this to get resolved, or try some native code debugging/fix.  (Or accept another color for that top bar.)

**Comment by DaleMcGrew** [comment]
:) We can wait for a fix. Thank you for doing the research and testing @SailingSteve. I have bumped this Issue to Priority 3.

**Comment by SailingSteve** [comment]
Suddenly started working with the Cordova scaffolding reinstall today.

**Comment by DaleMcGrew** [comment]
Hooray! :)

**Comment by DaleMcGrew** [comment]
The fix looks great!
