### ISSUE TITLE
Popup "hamburger" menu is covered by grayed out background

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#17]
If you scroll down to the very bottom of your ballot and then click the hamburger menu, it is hard to see because of the grayed out background.
![img_4596](https://user-images.githubusercontent.com/7756031/36858160-43fe8110-1d2f-11e8-986a-6639a5b80230.jpeg)

**Comment by SailingSteve** [comment]
Fixed in iOS build 7
