### ISSUE TITLE
Configure full-screen slide out for hamburger menu

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#21]
I have been looking at many Apps, and one thing they seem to share in common is the hamburger menu / settings screen tends to take over the entire screen. I think we should do the same. I think that the component we use for our Profile menu may have a "full screen" option?

I think we should also move the hamburger icon to the far right of the bottom bar.

Facebook example:
![img_4602](https://user-images.githubusercontent.com/7756031/36919270-968c18ce-1e11-11e8-9bfc-f8c4276b71e1.png)

Wikipedia example:
![img_4601](https://user-images.githubusercontent.com/7756031/36919275-9b4ac45a-1e11-11e8-82ba-8622d1982856.jpeg)

**Comment by SailingSteve** [comment]
Still have some menu loop bugs to resolve, but the menu is done (but not checked in)

<img width="598" alt="screen shot 2018-03-05 at 7 34 32 pm" src="https://user-images.githubusercontent.com/6923653/37013012-7685adae-20ac-11e8-94c5-0ce904d276f0.png">

**Comment by DaleMcGrew** [comment]
Very cool! I have been doing some parallel menu work that I will check in shortly.

**Comment by SailingSteve** [comment]
@DaleMcGrew  Does your work replace this work?  Should I put this work aside?

**Comment by DaleMcGrew** [comment]
@SailingSteve No it does not. I'm happy to discuss on the hangout, which I'm opening shortly.

**Comment by SailingSteve** [comment]
@DaleMcGrew 
This menu is based on react-slide-out that has a problem in our app, of sliding out too fast, maybe in a 1/10th of a second instead of a half.  I swapped react-slide-out for react-sliding-pane which had the same problem.

I looked at mango/slideout which claims Cordova compatibility.  This has a $18 per product license fee (I would have paid it in a second), but it hasn't had a core code fix in a year and has 33 open issues, and 13 open pull requests.  

So for now, I'd like to go with imperfect sliding until we have time to work on this more.

**Comment by DaleMcGrew** [comment]
@SailingSteve, I support your decision! Would it be possible for you to test the package you are choosing on WebApp, to see if the slide-out timing works in the direct WebApp bundle (on the website)? BTW, I've been looking at optimizations, and I think some of the slow-down comes from the 52 (!) API calls we make for the ballot to load. I think we can cut this in 1/2, which will decrease the work we are asking our browser clients to do.

**Comment by SailingSteve** [comment]
@DaleMcGrew  This is what it will look like with modal (Just a div on top of everything else)

<img width="598" alt="screen shot 2018-03-08 at 5 16 53 pm" src="https://user-images.githubusercontent.com/6923653/37185340-b400435c-22f4-11e8-90a1-abb5890b9456.png">

**Comment by DaleMcGrew** [comment]
Looks great @SailingSteve!

**Comment by SailingSteve** [comment]
react-tostify, that we use, relies on https://reactcommunity.org/react-transition-group/ that should do the job when we want to dig in again.

**Comment by DaleMcGrew** [comment]
Closing until we decide to open up the menu animations again.
