### ISSUE TITLE
Dragging down at top of Ballot, or up at bottom of Ballot

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#25]
When you are at the top of the ballot and you drag down, the header gets dragged down too. Instead, we want the header to remain stuck to the top of the screen, and the content below the header open up a little bit, and spring back when voter lets go (like how WebApp works in Safari browser.) The reverse is true when you are at the bottom of the Ballot and you drag up. (The footer should remain stuck to the bottom of the screen.

Space above header when dragging down:
![fullsizerender-9](https://user-images.githubusercontent.com/7756031/36947874-cc7bb64e-1f86-11e8-80e6-efb6853b70b4.jpg)

Space below footer when dragging up:
![fullsizerender-8](https://user-images.githubusercontent.com/7756031/36947904-333701ea-1f87-11e8-99ee-1ebc921d6edf.jpg)

**Comment by SailingSteve** [comment]
platforms/ios/WeVoteCordova/config.xml
    <preference name="DisallowOverscroll" value="true" />
    <preference name="UIWebViewBounce " value="false" />

**Comment by DaleMcGrew** [comment]
Fixed!
