### ISSUE TITLE
Footer goes away sometimes, and should always remain

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#31]
I believe we always want the footer navigation to show. Sometimes when I scroll long pages down (like the ballot), it goes away and it shouldn't. It does return a few seconds after stopping.

The only exception to this is when we go into "Theatre" mode, like:
https://wevote.us/wevoteintro/network

**Comment by SailingSteve** [comment]
@DaleMcGrew This is the issue we discussed this morning.  I've spent 8 hours o this so far, with no luck.  With headroom.js deactivated if Cordova, if you fast scroll the ballot, both menus disappear while re-rendering.  This is ugly, andg ives away the usage of Cordova if you are an expert, but the app is still fully functional.

I think the solution will be putting the ballot into a div that is a window into the scrollable area, and does not overlap either menu.  A fair amount of work, with more than usual potential effects on the webapp.

Suggest priority 2.

**Comment by DaleMcGrew** [comment]
Moved to priority 3.

**Comment by SailingSteve** [comment]
We may need to do this sooner, rather than later, it would be a change to Application.js and its sass.

See   [Plunker Demo](https://plnkr.co/edit/RQJWkGWgGjhA6kbUBQur?p=preview)

**Comment by DaleMcGrew** [comment]
Current implementation is fixed.
