### ISSUE TITLE
Search bar should fill full width of header bar-offset problem

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#32]
Currently the search box fills a little over 1/3rd of the header bar. Please make it fill the full width of the header bar.
![img_4633](https://user-images.githubusercontent.com/7756031/37494842-d284ed8c-2867-11e8-88a5-7e7425f10c99.jpeg)

**Comment by SailingSteve** [comment]
.search-cordova {
  width: 100%;
}

was 55%

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve! On Cordova there is now an offset problem, where the search results drop-down is shifted off screen to the left:
![img_4649](https://user-images.githubusercontent.com/7756031/37836391-8f325ea8-2e6f-11e8-8569-ac1f54e97950.jpeg)

**Comment by DaleMcGrew** [comment]
Verified!
