### ISSUE TITLE
Lower priority features that are disabled in Cordova

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#49]
- [ ] Re-enable Google analytics
- [ ] Figure out an alternative to "anchor href #" for the BallotSideBar -- one that works in Cordova
- [ ] "ReactPlayer" in About.jsx, worked for a while and now it doesn't.  Bet it is Content-Security-Policy related.  Works a bit in Android.
- [ ] Sideways scroll for a settings sub-menu in Cordova on the HamburgerMenu.
- [x] Re-enable "Polling Location" in HeaderSecondaryNavBar (WebApp uses an iFrame, yuck)
- [x] Login with Facebook
- [x] Login by email, in Android.  (Works in iOS)

**Comment by SailingSteve** [comment]
Im going to pass on "Move spinner up on first screen in Android", I spent a couple of hours modifying Java code (plugins/cordova-plugin-splashscreen/src/android/SplashScreen.java) and got the spinner to move to the right edge (I think native android assumes the phone is normally in landscape).  We can come back to this if it is important.

**Comment by SailingSteve** [comment]
I'm going to pass on "Print ballot, on the HeaderSecondaryNavBar" although it is possible with https://www.npmjs.com/package/cordova-plugin-printer, the plug in hasn't been maintained in 2 years, and we don't do printing in the webapp when responsive on a mobile device.

**Comment by DaleMcGrew** [comment]
Closing
