### ISSUE TITLE
Add "#WeVote" or "Twitter: @WeVote" to end of our Apple App Store name

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#72]
When a voter comes to the Apple App store and searches for "wevote", before you click "Search", a link to a competing app comes up as part of instant search. If we can add "WeVote" (one word) to either our app name or our description, I'm hoping a link to our app will appear in instant search. We currently have "WeVote" in our search terms, but that is not enough to get us to show up as part of instant search.

**Comment by SailingSteve** [comment]
@DaleMcGrew 
It looks like I can change the title.
How about.

"We Vote Voter Guide, WeVote!"

I could make another release with that styling change for the friends notification...

<img width="518" alt="screen shot 2018-07-19 at 8 36 09 pm" src="https://user-images.githubusercontent.com/6923653/42981881-6f881878-8b93-11e8-9edc-fbeb330e14bd.png">

**Comment by DaleMcGrew** [comment]
I have done some more testing, and have confirmed that we do need to put it into our product name for it to show up in the instant search. I'd like this text:
We Vote Voter Guide, from @WeVote 

Let's wait for a couple of weeks before we release another version, so we can weave in more changes. Thank you @SailingSteve.

**Comment by SailingSteve** [comment]
Testflight of 1.0.4 build 1

**Comment by SailingSteve** [comment]
@DaleMcGrew 

"We Vote Voter Guide, from @WeV" is the maximum length string allowed.
"We Vote Voter Guide,  @wevote" works

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve, "We Vote Voter Guide, @WeVote" (with upper case letter "w" and "v") looks fine.

**Comment by DaleMcGrew** [comment]
Verified.
