### ISSUE TITLE
Ballotpedia links in Cordova don't work

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#73]
Found on candidate detail pages

**Comment by SailingSteve** [comment]
@DaleMcGrew Is it intentional that the "Read more on Ballotpedia" link only appears in WebApp responsive device mode (and cCordova) and not in full screen browser mode?


<img width="629" alt="screen shot 2018-07-23 at 6 58 27 pm" src="https://user-images.githubusercontent.com/6923653/43114413-d3a23fb4-8eb3-11e8-8267-d3c033981aff.png">
<img width="663" alt="screen shot 2018-07-23 at 6 57 52 pm" src="https://user-images.githubusercontent.com/6923653/43114441-f6dc1b44-8eb3-11e8-9ad7-e3c0d3a631ca.png">

**Comment by DaleMcGrew** [comment]
Good catch @SailingSteve, the "Read More on Ballotpedia" link should appear for Desktop too.
