### ISSUE TITLE
iPhone X Display Problem with Camera Cutout

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#76]
On the iPhone X, our modals (in the App from the app store) are opening all the way at the top of the screen, wrapped around the camera cut-out. The voter wasn't able to click the "X" to close the modal.

Second, the notification messages when you select issues were displaying all the way at the top, so the camera cut-out was in the way.

There were also problems with the navigation in the footer.

(I'm working on getting a screenshot.)

**Comment by DaleMcGrew** [comment]
@SailingSteve would you be willing to take on this issue?

**Comment by DaleMcGrew** [comment]
Here is the iPhone X screenshot:
![iphonex-screen](https://user-images.githubusercontent.com/7756031/45603876-85e6a480-b9e3-11e8-90b0-c8a4218ff738.png)

**Comment by SailingSteve** [comment]
@DaleMcGrew Done with the code, and testing now.  I have code in place for the new iPhone xs max, but there is no simulator for it yet, so I'll have to retest later.

**Comment by DaleMcGrew** [comment]
Thank you @SailingSteve! Were you able to test in XCode against an iPhone X simulator?

**Comment by SailingSteve** [comment]
Tested on:  iPhone 7, 8, 8 plus, & X in simulators and on a iPhone 7 plus device.
Also tested Webapp full screen, and responsive in iPhone 6 size.
All looks pretty good -- there are some very minor layout issues that could use attention.
Not able to test on the newest  iPhone XS or iPhone XS Max, as there are no simulators yet.

**Comment by SailingSteve** [comment]
Working, but maybe we will want a more elegant solution someday.
