### ISSUE TITLE
Ballot scrolls incorrectly when "View all ..." is clicked.  iPhone XS Max, and others.

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#77]
![simulator screen shot - iphone xs max - 2018-09-20 at 13 32 04](https://user-images.githubusercontent.com/6923653/45845356-bf682a00-bcd9-11e8-98a1-ed8ce603c041.png)
![simulator screen shot - iphone xs max - 2018-09-20 at 13 32 16](https://user-images.githubusercontent.com/6923653/45845361-c1ca8400-bcd9-11e8-8afe-70cc91fd779c.png)

**Comment by DaleMcGrew** [comment]
Closing this because we are going to take the voter to a page dedicated to the office as opposed to unfurling.
