### ISSUE TITLE
Layout problems on iPhone X, XS, XR and XS Max

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#78]
- [x] Toast message is obscured by the notch. (showToast.js)
- [x] X to close works on iPhone 8p, but not on the XS Max, Make your positions public
- [x] Back to button clipped on the top on XS Max
- [x] Similar layout issues with toast and Make your positions public, on XR
- [ ] Modal scrolls out of protected area iPhone XR
- [x] The google find address pulldown detaches and sticks to all screens (Did not reproduce)

**Comment by SailingSteve** [comment]
After fix with marginTop at 50px, checked in at 30 which looks better:
<img width="526" alt="screen shot 2018-09-26 at 2 07 52 pm" src="https://user-images.githubusercontent.com/6923653/46109585-e28d5080-c195-11e8-8b80-04b77166d186.png">

<img width="487" alt="screen shot 2018-09-21 at 4 36 17 pm" src="https://user-images.githubusercontent.com/6923653/45910274-ba2fdb80-bdbc-11e8-8365-b186291e774a.png">

Second similar problem, the google find address pulldown detaches and sticks to all screens
**9/27/18:  I was unable to reproduce this after 20 minutes of trying**

<img width="526" alt="screen shot 2018-09-22 at 10 17 28 am" src="https://user-images.githubusercontent.com/6923653/45919853-f6148080-be50-11e8-85ce-211b602360e1.png">

**Comment by SailingSteve** [comment]
X to close works on iPhone 8p, but not on the XS Max

<img width="402" alt="screen shot 2018-09-22 at 10 25 30 am" src="https://user-images.githubusercontent.com/6923653/45919915-fc572c80-be51-11e8-9d73-0713b4bbfa5a.png">
<img width="526" alt="screen shot 2018-09-22 at 10 25 45 am" src="https://user-images.githubusercontent.com/6923653/45919918-00834a00-be52-11e8-823a-93367af9aa59.png">

**Comment by SailingSteve** [comment]
<img width="526" alt="screen shot 2018-09-26 at 12 46 50 pm" src="https://user-images.githubusercontent.com/6923653/46105251-70633e80-c18a-11e8-888f-c8bfe10bcee1.png">

**Comment by SailingSteve** [comment]
<img width="526" alt="screen shot 2018-09-26 at 3 27 37 pm" src="https://user-images.githubusercontent.com/6923653/46113613-f8a20d80-c1a3-11e8-923c-16e15d61eb53.png">

**Comment by SailingSteve** [comment]
<img width="394" alt="screen shot 2018-09-26 at 4 49 15 pm" src="https://user-images.githubusercontent.com/6923653/46115527-3dca3d80-c1ac-11e8-8a93-2c5287d42b5e.png">
<img width="394" alt="screen shot 2018-09-26 at 4 48 53 pm" src="https://user-images.githubusercontent.com/6923653/46115533-402c9780-c1ac-11e8-8006-9f27eb17f79c.png">

**Comment by DaleMcGrew** [comment]
Fixed.
