### ISSUE TITLE
Slick-Slider layout problems on iPhone XR & XS Max,  Send this ballot to yourself

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#82]
I've spent 4 hours on this, and it is inconsistent, styling changes don't seem to effect it. 

<img width="526" alt="screen shot 2018-09-26 at 12 46 50 pm" src="https://user-images.githubusercontent.com/6923653/46105251-70633e80-c18a-11e8-888f-c8bfe10bcee1.png">

**Comment by SailingSteve** [comment]
**There is also weird behavior on the desktop** if you scroll back to the first pand by dragging the surface of the pane... the slider disappears, and there is no gap between the panes.  Clicking the dots at the bottom works fine.

I confirmed this on the live wevote.us instance (before I introduced all these npm package updates for this issue).

**Comment by DaleMcGrew** [comment]
Fixed.
