### ISSUE TITLE
New ugly message from facebook/apple on iOS -- need to avoid it

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#90]
https://stackoverflow.com/questions/50448989/requirement-to-change-app-name-in-google-sign-in-alert

<img width="584" alt="screen shot 2018-11-07 at 1 35 00 pm" src="https://user-images.githubusercontent.com/6923653/48162531-352c5300-e292-11e8-880b-453758621534.png">

**Comment by DaleMcGrew** [comment]
Are we able to change our Bundle name to "We Vote"? "WeVote" would be ok, but less ideal. @SailingSteve, am I correct that this issue is about changing that Bundle name, as opposed to trying to avoid the alert?

**Comment by SailingSteve** [comment]
I made a change (like one from months ago) so that the dialog does not appear anymore.  This problem no longer reproduces.
