### ISSUE TITLE
Header styles: Upon sign out, Sign In page scrolled above header

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#91]
When you sign out, you are returned to the Sign In page. The page is scrolled though with some text that is hidden under the "Back to Settings" header.

Please test all header changes in the browser-based WebApp as well.

![img_5683](https://user-images.githubusercontent.com/7756031/48230749-eef1f500-e360-11e8-8a09-ca99c0a28817.jpeg)

I suspect that the settings page being rendered under the "Back to Settings" page shown here is related:
![img_5690](https://user-images.githubusercontent.com/7756031/48231459-0d58f000-e363-11e8-9bcb-f4ff76e9977f.jpeg)

**Comment by SailingSteve** [comment]
No longer reproduces
