### ISSUE TITLE
Header Styles: Following Facebook sign in, page displays under header

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteCordova#95]
Following Facebook sign in, page displays under header.

Please test all header changes in the browser-based WebApp as well.

![img_5689](https://user-images.githubusercontent.com/7756031/48231363-ab988600-e362-11e8-852f-85772220e751.jpeg)

**Comment by SailingSteve** [comment]
![img_f577118ee056-1](https://user-images.githubusercontent.com/6923653/49701922-42956f80-fba7-11e8-9127-4e7555afca9a.jpeg)

**Comment by SailingSteve** [comment]
Looks good now

**Comment by DaleMcGrew** [comment]
Fixed.
